name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            # Update repository
            cd ~/repositories/atzimju_uzskaites_sistema
            git checkout production
            git pull origin production
            
            # Copy build (should be built in advance)
            # to web server and restart nginx
            cd react_app
            cp -r build/* /var/www/grade/html/
            sudo systemctl restart nginx
            
            # Build go_backend
            cd ../go_backend
            go build           
            
